// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdbdhaddcagafzjtwitg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYmRoYWRkY2FnYWZ6anR3aXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODEwMDYsImV4cCI6MjA3NDQ1NzAwNn0.T5AlFNLNUf8mXuY0mcCgWDnlXzgF4Hyp2zhs4xGnMh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});