// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oadgcamhctoudsivxmzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZGdjYW1oY3RvdWRzaXZ4bXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjcwNDcsImV4cCI6MjA3NDM0MzA0N30.Z48kCkuRt_t5GLSwBvctVx74UYRigXlmqCDiA8eas-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});